"""LangGraph orchestration (design doc 4.2).

Model each workflow as a small, single-purpose, checkpointed graph rather than
one giant graph. Checkpointing lets a 'waiting for your approval' state survive a
restart; the human-in-the-loop interrupt/resume primitives are what make rung-2
autonomy (propose, wait) work.

The autonomy gate (``autonomy.py``) is consulted before any action leaves a
graph, and it fails safe: without an explicit per-(action,domain) grant, the
graph always routes through human approval.
"""

from .attention import (
    AttentionItem,
    AttentionStore,
    JsonAttentionStore,
    SqliteAttentionStore,
    open_attention_store,
)
from .batch import (
    MIN_BATCH_SIZE,
    BatchGroup,
    group_pending_by_capability,
    render_batch_card,
    resolve_batch_approve_all,
)
from .autonomy import (
    Action,
    Domain,
    GrantScope,
    PermissionMatrix,
    RiskTier,
    Rung,
    ScopedGrant,
    default_matrix,
    max_rung_for_risk_tier,
)
from .capabilities import (
    Capability,
    CapabilityRegistry,
    build_capability_registry,
    capability_gates_pass,
    make_accept_invite_apply_fn,
    make_add_label_apply_fn,
    make_create_hold_compensate_fn,
    make_decline_invite_compensate_fn,
    make_draft_reply_compensate_fn,
    make_label_compensate_fn,
    make_mark_read_apply_fn,
    make_remove_label_apply_fn,
    make_reschedule_compensate_fn,
    make_tentative_invite_apply_fn,
)
from .correlation import (
    CorrelatableItem,
    correlate,
    from_attention_item,
    from_calendar_event,
    from_mail_thread,
)
from .state import DraftApproveState
from .draft_approve import (
    HYGIENE_ACTIONS,
    apply_confirmation,
    archive_draft_fn,
    build_draft_approve_graph,
    calendar_action_draft_fn,
    make_calendar_action_apply_fn,
    make_connector_apply_fn,
    make_label_apply_fn,
    resume_workflow,
)
from .followup import (
    JsonNudgeState,
    SqliteNudgeState,
    find_nudge_candidates,
    open_nudge_state,
    run_follow_up_nudges,
)
from .grants import (
    DEMOTION_PREFIX,
    GRADUATION_CARD_EXCLUDED_ACTIONS,
    GRADUATION_CARD_MAX_RUNG,
    GRADUATION_PREFIX,
    GRADUATION_REJECTION_COOLDOWN_DAYS,
    MAX_AUTONOMY_CARDS_PER_RUN,
    DemotionSuggestion,
    GraduationSuggestion,
    JsonGraduationState,
    JsonPermissionMatrixStore,
    SqliteGraduationState,
    TrackRecord,
    demotion_thread_id,
    grant,
    graduation_thread_id,
    open_graduation_state,
    parse_scope,
    render_scope,
    resolve_autonomy_card,
    revoke,
    show_matrix,
    suggest_demotions,
    suggest_graduations,
    track_records,
    track_records_by_scope,
)
from .importance import (
    DECAY_DAYS,
    MAX_SIGNALS,
    ImportanceProfile,
    ImportanceTier,
    JsonImportanceProfile,
    SqliteImportanceProfile,
    TierAssessment,
    assess_from_signals,
    open_importance_profile,
)
from .ledger import (
    EDIT_SECTIONS,
    BulletAttribution,
    ContextAttribution,
    DecisionLedger,
    EditMetrics,
    LedgerRow,
    MetricsSlice,
    SqliteDecisionLedger,
    classify_edit_sections,
    compute_bullet_attribution,
    compute_edit_metrics,
    compute_metrics_slice,
    record_decision,
    record_proposal,
    render_bullet_attribution_table,
    render_metrics_table,
    window_rows,
)
from .pending import (
    DEFAULT_EXPIRY,
    STATUS_EXPIRED,
    STATUS_IGNORED,
    STATUS_PENDING,
    STATUS_RESOLVED,
    JsonPendingApprovals,
    PendingApproval,
    PendingApprovals,
    SqlitePendingApprovals,
    open_pending_approvals,
    sweep_expired,
    sweep_ignored,
)
from .triage import Priority, TriageResult, triage_thread
from .scheduling import ConflictResult, detect_conflict
from .undo import UNDO_WINDOW, UndoError, UndoResult, undo_effect

__all__ = [
    "MIN_BATCH_SIZE",
    "BatchGroup",
    "group_pending_by_capability",
    "render_batch_card",
    "resolve_batch_approve_all",
    "Action",
    "Domain",
    "Rung",
    "RiskTier",
    "max_rung_for_risk_tier",
    "PermissionMatrix",
    "GrantScope",
    "ScopedGrant",
    "default_matrix",
    "Capability",
    "CapabilityRegistry",
    "build_capability_registry",
    "capability_gates_pass",
    "make_accept_invite_apply_fn",
    "make_add_label_apply_fn",
    "make_create_hold_compensate_fn",
    "make_decline_invite_compensate_fn",
    "make_draft_reply_compensate_fn",
    "make_label_compensate_fn",
    "make_mark_read_apply_fn",
    "make_remove_label_apply_fn",
    "make_reschedule_compensate_fn",
    "make_tentative_invite_apply_fn",
    "DraftApproveState",
    "apply_confirmation",
    "archive_draft_fn",
    "build_draft_approve_graph",
    "calendar_action_draft_fn",
    "make_calendar_action_apply_fn",
    "make_connector_apply_fn",
    "make_label_apply_fn",
    "resume_workflow",
    "HYGIENE_ACTIONS",
    "JsonNudgeState",
    "SqliteNudgeState",
    "open_nudge_state",
    "find_nudge_candidates",
    "run_follow_up_nudges",
    "GraduationSuggestion",
    "DemotionSuggestion",
    "JsonPermissionMatrixStore",
    "JsonGraduationState",
    "SqliteGraduationState",
    "open_graduation_state",
    "TrackRecord",
    "grant",
    "revoke",
    "parse_scope",
    "render_scope",
    "show_matrix",
    "suggest_graduations",
    "suggest_demotions",
    "track_records",
    "track_records_by_scope",
    "resolve_autonomy_card",
    "graduation_thread_id",
    "demotion_thread_id",
    "GRADUATION_PREFIX",
    "DEMOTION_PREFIX",
    "GRADUATION_CARD_EXCLUDED_ACTIONS",
    "GRADUATION_CARD_MAX_RUNG",
    "GRADUATION_REJECTION_COOLDOWN_DAYS",
    "MAX_AUTONOMY_CARDS_PER_RUN",
    "JsonPendingApprovals",
    "SqlitePendingApprovals",
    "open_pending_approvals",
    "PendingApproval",
    "PendingApprovals",
    "sweep_ignored",
    "sweep_expired",
    "STATUS_PENDING",
    "STATUS_RESOLVED",
    "STATUS_IGNORED",
    "STATUS_EXPIRED",
    "DEFAULT_EXPIRY",
    "ImportanceProfile",
    "ImportanceTier",
    "JsonImportanceProfile",
    "SqliteImportanceProfile",
    "open_importance_profile",
    "TierAssessment",
    "assess_from_signals",
    "DECAY_DAYS",
    "MAX_SIGNALS",
    "Priority",
    "TriageResult",
    "triage_thread",
    "ConflictResult",
    "detect_conflict",
    "AttentionItem",
    "AttentionStore",
    "JsonAttentionStore",
    "SqliteAttentionStore",
    "open_attention_store",
    "CorrelatableItem",
    "correlate",
    "from_attention_item",
    "from_calendar_event",
    "from_mail_thread",
    "EDIT_SECTIONS",
    "BulletAttribution",
    "ContextAttribution",
    "DecisionLedger",
    "EditMetrics",
    "LedgerRow",
    "MetricsSlice",
    "SqliteDecisionLedger",
    "classify_edit_sections",
    "compute_bullet_attribution",
    "compute_edit_metrics",
    "compute_metrics_slice",
    "record_decision",
    "record_proposal",
    "render_bullet_attribution_table",
    "render_metrics_table",
    "window_rows",
    "UNDO_WINDOW",
    "UndoError",
    "UndoResult",
    "undo_effect",
]
